# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot_arm
  joint_model_group_pose: start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_joint
    - arm_segment_2
    - arm_segment_3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
controller_list:
  -name: 
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  #controller_list:
  #I changed robot_arm_controller to arm_controller
  #- name: arm_controller
arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - base_joint
      - arm_segment_2
      - arm_segment_3
    constraints:
      goal_time: 0.6
      # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
      stopped_velocity_tolerance: 0
      base_joint: {trajectory: 0.1, goal: 0.1}
      arm_segment_2: {trajectory: 0.1, goal: 0.1}
      arm_segment_3: {trajectory: 0.1, goal: 0.1}

controller_list:
- name: arm_controller
  action_ns: follow_joint_trajectory
  default: True
  type: FollowJointTrajectory
  joints:
    - base_joint
    - arm_segment_2
    - arm_segment_3